### ISSUE TITLE
rel_num wrong. vim.py line 162. real_num=int(FLAGS.No*(FLAGS.N0-1))

### ISSUE THREAD

**Issue by chaofiber** [jaesik817/visual-interaction-networks_tensorflow#11]

**Comment by jsikyoon** [comment]
Hi, Thank you for your interesting about my repo.

Let me know the reason why you think it is wrong?

**Comment by chaofiber** [comment]
Hello,

My understanding is that rel_num (line 163 in vin.py) should be the number of relations between all objects. So fo n objects, it should be n(n-1); The current code works because in the case of n=3, 3*(3+1)/2=3*(3-1); If you change the number of objects, you will find the code doesn't work ( Out of bound error in line 186, vin.py)

**Comment by jsikyoon** [comment]
ah okay thank you I'll fix that.
