### ISSUE TITLE
Implementation Difference

### ISSUE THREAD

**Issue by Seleucia** [jaesik817/visual-interaction-networks_tensorflow#2]
Hello,
Thank you for implementation. I was checking your code and i saw some difference at implementation between paper and your code. for example: according to the supplementary material you should first concatenate and apply a linear layer, but you are for applying a linear layer and then doing the concatenation [op](https://github.com/jaesik817/visual-interaction-networks_tensorflow/blob/master/vin.py#L118) why do you need this difference?

**Comment by jsikyoon** [comment]
hi,
could I know more detail information of different parts?

I will check that and talk to you the reason 

thanks.

jaesik.

**Comment by Seleucia** [comment]
Please have a look Page 11
https://arxiv.org/pdf/1706.01433.pdf

There are  few more differences, for example you are feeding 6 image, but according to supplementary material they feed only 3.

**Comment by jsikyoon** [comment]
Thank you for reply!!

I checked my code.

1. according to the supplementary material you should first concatenate and apply a linear layer, but you are for applying a linear layer and then doing the concatenation op why do you need this difference?
=> pair1-5 concatenated on sample channel before linear layer for making grouped input of the layer.
     The concatenation as mentioned in paper is implemented at 124-7 lines on vin.py script.

 2. for example you are feeding 6 image, but according to supplementary material they feed only 3.
=> For designing Dynamics Predictor, 4 state codes are used as input. Each state code is generated with three imgs, thus total 6 imgs are needed for one sample.

Thanks.

Jaesik.

**Comment by jsikyoon** [comment]
if you do not have any other issues, then I will close this
