### ISSUE TITLE
TypeError: 'range' object does not support item assignment

### ISSUE THREAD

**Issue by dtchang** [jaesik817/visual-interaction-networks_tensorflow#3]
Changed
np.random.shuffle(..._idx);
to
np.random.shuffle(list(..._idx));
for it to work for python3.

**Comment by PyPatel** [comment]
Please have a look at the current pull request. It will solve the issue. In Python3 range is a generator object - it does not return a list. Convert it to a list before shuffling.

**Comment by jsikyoon** [comment]
Thanks PyPatel.
