### ISSUE TITLE
TypeError range object doesn’t support item assignment

### ISSUE THREAD

**Issue by syngef01** [jaesik817/visual-interaction-networks_tensorflow#9]
def swap (sequence, i,j):
               temp = sequence[i]
               sequence[i] = sequence[j]
I am new in python and I would like to solve this issue. Thank you for your help !

**Comment by jsikyoon** [comment]
Hi

Python variable is based on pointer,

Thus if you want to do swap then copy library can be one option.

Example of copy lib.

import copy

a0=1
a1=copy.copy(a0)
a2=a0
a0=2
print(a0,a1,a2)

Thanks.

BRs, Jaesik.

2018년 5월 7일 (월) 오후 1:47, syngef01 <notifications@github.com>님이 작성:

**Comment by syngef01** [comment]
Thank you I will try and I will let you know 😉😊

**Comment by syngef01** [comment]
after applying I got this. Kindly find attached the picture of the error
got.

2018-05-07 13:54 GMT+05:30 loïs ben <loisben0@gmail.com>:

> Thank you I will try and I will let you know 😉😊
>
> Sent from my iPhone
>

**Comment by syngef01** [comment]
2018-05-08 11:28 GMT+05:30 loïs ben <loisben0@gmail.com>:

**Comment by jsikyoon** [comment]
could you copy the err on here? 

Thanks.

Jaesik.

**Comment by syngef01** [comment]
File "c:\Users\Tanoe\Documents\Project
Final\CODE\modifiedCuckooSearchAlgoritm\cuckoo.py", line 26, in swap
    sequence[j] = copy.copy(sequence[i])
TypeError: 'range' object does not support item assignment
PS C:\Users\Tanoe\Documents\Project Final\CODE\modifiedCuckooSearchAlgoritm>

2018-05-08 15:07 GMT+05:30 Jaesik Yoon <notifications@github.com>:

**Comment by jsikyoon** [comment]
hm,

I tested your swap on my side (not using copy)

that is working.

plz check your ones again.

>>> a = [1,2,3]
>>> tmp = a[1]
>>> a[1] = a[2]
>>> a
[1, 3, 3]
>>> a[2] = tmp
>>> a
[1, 3, 2]
>>>

**Comment by syngef01** [comment]
Ok 👍🏾
